include:
- ./func/*
kind: ArchiveUploadSpec
name: func-mg5t

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: env-get-employ-status-us-2523f931-0c00-48ab-86c2-01c2420fb98b
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-employ-status-us
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-mg5t
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-08-01T17:39:03Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: env-get-employ-status-us
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-employ-status-us
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: env-get-employ-status-us-2523f931-0c00-48ab-86c2-01c2420fb98b
      namespace: default
  requestsPerPod: 1
  resources: {}
