include:
- ./func/*
kind: ArchiveUploadSpec
name: func-rkoL

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: env-get-employ-status-us-38899032-7cfd-4318-bc95-4faaad4c6c5a
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-employ-status-us
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-rkoL
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-20T17:54:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: env-get-employ-status-us
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-employ-status-us
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_employment_status_enum
    packageref:
      name: env-get-employ-status-us-38899032-7cfd-4318-bc95-4faaad4c6c5a
      namespace: default
  requestsPerPod: 1
  resources: {}
