apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: onb-us-enum-jb-stat-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onb-us-enum-jb-stat-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/employ_status_us
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/employ_status_us
