include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-esXX

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-us-enum-jb-stat-fn-5494e0d1-f544-4895-8898-89a4664263cc
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-esXX
  environment:
    name: onb-us-enum-jb-stat-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T10:23:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-us-enum-jb-stat-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-us-enum-jb-stat-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-us-enum-jb-stat-fn-5494e0d1-f544-4895-8898-89a4664263cc
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
