apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: route-get-employ-status-us
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: env-get-employ-status-us
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/employ_status_us
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/employ_status_us
